'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, Building2, Check, Download, Loader2, Phone, Play, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Progress } from '@/components/ui/progress';
import { INDUSTRIES, DEMO_MODEL, assessmentSchema, estimate, profileSchema, wordCount, emptyPriorities, prioritiesSchema, type Assessment } from '@/lib/assessment';

import SuccessorPrioritiesPanel from './successor-priorities';
import { BuyerPractice, SaleReadinessGuide } from './sale-preparation';

type Draft={revenue:string;profit:string;year:string;employees:string;industry:string;location:string};
const empty:Draft={revenue:'',profit:'',year:'2025',employees:'',industry:'',location:''};
const euro=(n:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
function Consent({id,checked,onChange,title,copy}:{id:string;checked:boolean;onChange:(value:boolean)=>void;title:string;copy:string}){return <div className="choice"><Checkbox id={id} checked={checked} onCheckedChange={v=>onChange(v===true)}/><label htmlFor={id}><strong>{title}</strong><span>{copy}</span></label></div>}
function Step({label,title,body,children,error,onBack,onNext,next}:{label:string;title:string;body:string;children:React.ReactNode;error:string;onBack?:()=>void;onNext:()=>void;next:string}){return <section className="work-card guided-card"><div className="card-progress"><span>{label}</span><Progress value={Number(label.slice(5,6))/3*100}/></div><h2>{title}</h2><p className="guided-lead">{body}</p>{children}{error&&<p className="error" role="alert">{error}</p>}<div className="actions">{onBack?<Button variant="ghost" onClick={onBack}><ArrowLeft size={16}/> Back</Button>:<span/>}<Button className="primary" onClick={onNext}>{next}<ArrowRight size={17}/></Button></div></section>}

export default function GuidedQuickCheck({signedIn}:{signedIn:boolean}){
 const [page,setPage]=useState(1);const [draft,setDraft]=useState<Draft>(empty);const [assessment,setAssessment]=useState<Assessment|null>(null);const [error,setError]=useState('');const [company,setCompany]=useState('');const [email,setEmail]=useState('');const [culture,setCulture]=useState('');const [save,setSave]=useState(false);const [contact,setContact]=useState(false);const [shareCulture,setShareCulture]=useState(false);const [busy,setBusy]=useState(false);const [saved,setSaved]=useState(false);const audio=useRef<HTMLAudioElement>(null);
 const [priorities,setPriorities]=useState(emptyPriorities);
 useEffect(()=>{const raw=sessionStorage.getItem('mergero-guided-draft');if(!raw)return;sessionStorage.removeItem('mergero-guided-draft');try{const d=JSON.parse(raw);const a=assessmentSchema.safeParse(d.assessment);if(!a.success)return;setAssessment(a.data);setDraft(d.draft);setCompany(d.company||'');setEmail(d.email||'');setCulture(d.culture||'');setContact(d.contact===true);setShareCulture(d.shareCulture===true);const p=prioritiesSchema.safeParse(d.priorities);if(p.success)setPriorities(p.data);setPage(5);}catch{/* Discard invalid draft. */}},[]);
 function keepDraft(){sessionStorage.setItem('mergero-guided-draft',JSON.stringify({draft,assessment,company,email,culture,contact,shareCulture,priorities}));}
 const edit=(key:keyof Draft,value:string)=>{setDraft(old=>({...old,[key]:value}));setError('')};
 const toProfit=()=>{if(!Number(draft.revenue)||Number(draft.revenue)<=0){setError('Enter an annual revenue above zero.');return;}setPage(2)};
 const toContext=()=>{if(!draft.profit.trim()||!draft.year.trim()){setError('Enter operating profit and the financial year.');return;}setPage(3)};
 const finishNumbers=()=>{const parsed=assessmentSchema.safeParse({...draft,revenue:Number(draft.revenue),profit:Number(draft.profit),employees:Number(draft.employees),year:Number(draft.year)});if(!parsed.success){setError(parsed.error.issues[0]?.message||'Please complete the business details.');return;}setAssessment(parsed.data);setPage(4)};
 const saveProfile=async(e:FormEvent)=>{e.preventDefault();if(!assessment)return;const parsed=profileSchema.safeParse({assessment,company,email,saveConsent:true,buyerVisible:contact,contactConsent:contact,culture,cultureShareConsent:shareCulture,successorPriorities:priorities});if(!parsed.success){setError(parsed.error.issues[0]?.message||'Please check your profile details.');return;}setBusy(true);setError('');try{const response=await fetch('/api/profiles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(parsed.data)});const data=await response.json() as {error?:string};if(!response.ok)throw Error(data.error);setSaved(true);setPage(6)}catch(e){setError(e instanceof Error?e.message:'Profile could not be saved.');}finally{setBusy(false)}};
 const result=assessment?estimate(assessment):null;
 const reset=()=>{setDraft(empty);setAssessment(null);setPage(1);setError('');setCompany('');setEmail('');setCulture('');setSave(false);setContact(false);setShareCulture(false);setSaved(false);setPriorities(emptyPriorities())};
 return <main className="app-shell"><header className="site-header"><a className="brand" href="/" aria-label="Mergero home"><span className="brand-symbol">m</span>mergero<span className="brand-dot">.</span></a><span className="header-caption">A clearer first step.</span><a className="buyer-nav" href="/seller">Seller account</a><a className="buyer-nav" href="/buyer"><Building2 size={15}/> Buyer portal</a><span className="demo-label">Working demo</span></header><div className="guided-layout"><aside className="intro"><span className="eyebrow">MERGERO QUICK CHECK</span><h1>One clear question<br/>at a <em>time.</em></h1><p>A quick orientation based on the numbers you know. Your data remains in this browser until you choose to save it.</p><ol className="steps"><li className={page<=3?'active':'complete'}><span>{page>3?<Check size={16}/>:1}</span>Business figures</li><li className={page===4?'active':page>4?'complete':''}><span>{page>4?<Check size={16}/>:2}</span>Your estimate</li><li className={page>=5?'active':''}><span>3</span>Your choice</li></ol><div className="aside-note"><ShieldCheck size={20}/><p>A saved profile is separate from permission to appear to buyers or be contacted.</p></div></aside><div className="guided-workspace">
 {page===1&&<Step label="STEP 1 OF 3" title="What was your annual revenue?" body="Use the last completed financial year. An approximate number is fine." error={error} onNext={toProfit} next="Continue"><div className="single-field"><label htmlFor="revenue">Annual revenue</label><div className="money-input"><span>€</span><Input id="revenue" autoFocus type="number" min="1" max="1000000000000" step="0.01" placeholder="e.g. 400,000" value={draft.revenue} onChange={e=>edit('revenue',e.target.value)}/></div><p className="hint">You can correct this before you see the estimate.</p></div></Step>}
 {page===2&&<Step label="STEP 2 OF 3" title="How profitable was the business?" body="Use operating profit before interest and tax (EBIT), for the same period as revenue." error={error} onBack={()=>setPage(1)} onNext={toContext} next="Continue"><div className="field-grid"><div className="field"><label htmlFor="profit">Annual operating profit</label><div className="money-input"><span>€</span><Input id="profit" autoFocus type="number" step="0.01" placeholder="e.g. 70,000" value={draft.profit} onChange={e=>edit('profit',e.target.value)}/></div></div><div className="field"><label htmlFor="year">Financial year</label><Input id="year" type="number" min="2000" max={new Date().getFullYear()} value={draft.year} onChange={e=>edit('year',e.target.value)}/></div></div></Step>}
 {page===3&&<Step label="STEP 3 OF 3" title="A little context for the business." body="These details make the profile useful for a later buyer conversation." error={error} onBack={()=>setPage(2)} onNext={finishNumbers} next="See my estimate"><div className="field-grid"><div className="field"><label htmlFor="employees">Employees</label><Input id="employees" autoFocus type="number" min="0" step="1" placeholder="e.g. 6" value={draft.employees} onChange={e=>edit('employees',e.target.value)}/></div><div className="field"><label htmlFor="industry">Industry</label><Select value={draft.industry} onValueChange={v=>edit('industry',v)}><SelectTrigger id="industry" className="select-input"><SelectValue placeholder="Choose an industry"/></SelectTrigger><SelectContent>{INDUSTRIES.map(item=><SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div className="field"><label htmlFor="location">Country or region</label><Input id="location" placeholder="e.g. Finland" value={draft.location} onChange={e=>edit('location',e.target.value)}/></div></div></Step>}
 {page===4&&assessment&&result&&<section className="work-card guided-card"><div className="card-progress"><span>YOUR RESULT</span><Progress value={100}/></div><h2>Your starting point.</h2><p className="guided-lead">This is an illustrative orientation, not a formal valuation.</p><div className="estimate"><span className="small-label">ILLUSTRATIVE BUSINESS VALUE</span>{result.low===null?<><h3>A closer look is needed</h3><p>A profit-multiple model cannot provide a useful range when operating profit is zero or negative.</p></>:<><div className="value-range">{euro(result.low)}<span>to</span>{euro(result.high!)}</div><p>{euro(assessment.profit)} EBIT × {DEMO_MODEL.low}–{DEMO_MODEL.high}</p></>}</div><div className="result-facts"><div><span>Revenue</span><strong>{euro(assessment.revenue)}</strong></div><div><span>Operating margin</span><strong>{result.margin.toFixed(1)}%</strong></div><div><span>Employees</span><strong>{assessment.employees}</strong></div></div><div className="model-note"><span className="small-label">HOW THIS DEMO WORKS</span><p>It applies an illustrative 3–5× operating-profit range. Debt, cash, recurring revenue, customer concentration, growth and owner dependency are excluded.</p></div><div className="actions"><Button variant="ghost" onClick={()=>setPage(3)}><ArrowLeft size={16}/> Edit details</Button><Button className="primary" onClick={()=>setPage(5)}>Choose what happens next <ArrowRight size={17}/></Button></div></section>}
 {page===5&&<form className="work-card guided-card" onSubmit={saveProfile}><div className="card-progress"><span>YOUR CHOICE</span><Progress value={100}/></div><h2>Save a profile, if you want to.</h2><p className="guided-lead">The result is already yours. Saving a profile is optional.</p><div className="conversation-options"><button className="call-preview" type="button" onClick={()=>audio.current?.play()}><span className="call-icon"><Phone size={21}/></span><span><strong>Listen to a mock discovery call</strong><small>No real call, microphone or recording.</small></span><Play size={19}/></button>{assessment&&<BuyerPractice assessment={assessment}/>}</div><audio className="mock-audio" ref={audio} controls preload="none" src="/mergero-demo-call.wav"/><div className="field-grid"><div className="field"><label htmlFor="company">Company name</label><Input id="company" required value={company} onChange={e=>setCompany(e.target.value)}/></div><div className="field"><label htmlFor="email">Contact email</label><Input id="email" required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></div></div><Consent id="contact" checked={contact} onChange={setContact} title="Make this profile visible to approved buyers" copy="If a buyer sees a potential fit, they may contact you using the email you provide. There is no commitment to continue a conversation."/><SaleReadinessGuide/><div className="culture-heading"><h3>Business culture</h3><span>Optional</span></div><Textarea placeholder="What should a future buyer preserve?" value={culture} maxLength={8000} onChange={e=>{setCulture(e.target.value);if(!e.target.value)setShareCulture(false)}}/><p className="word-count">{wordCount(culture)} / 500 words</p><SuccessorPrioritiesPanel value={priorities} onChange={setPriorities}/><Consent id="culture" checked={shareCulture} onChange={setShareCulture} title="Share my culture statement with buyers" copy="Only available when the profile is visible to buyers."/>{error&&<p className="error" role="alert">{error}</p>}<div className="actions"><Button type="button" variant="ghost" onClick={()=>setPage(4)}><ArrowLeft size={16}/> Back</Button>{signedIn?<Button type="submit" className="primary" disabled={busy}>{busy?<Loader2 className="spin" size={17}/>:null}Save my profile</Button>:<div className="account-cta"><a className="link-button" href="/signin-with-chatgpt?return_to=/" target="_top" onClick={keepDraft}>Create account and keep your profile on record</a><p>Creating an account keeps your entry private to you unless you choose buyer visibility. If you do, verified buyers can view it and may contact you if they see a possible fit. There is no obligation to respond or proceed.</p></div>}</div></form>}
 {page===6&&<section className="work-card completion"><span className="completion-icon"><Check size={34}/></span><h2>{saved?'Your profile is saved.':'Your check is complete.'}</h2><p>{saved&&contact?'Approved buyers can now find this profile and contact you. You can disable that permission in a later profile-management update.':saved?'Your profile is stored privately. Buyer visibility is off.':'No profile or contact details were saved.'}</p><div className="actions"><a className="link-button" href="/seller">View my seller account</a><Button className="primary" onClick={reset}>Start a new check <ArrowRight size={17}/></Button></div></section>}
 </div></div></main>;
}
